"""add bio & pic path col

Revision ID: 241e4ca58d0c
Revises: 86ad9244befd
Create Date: 2020-05-09 23:28:12.681465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241e4ca58d0c'
down_revision = '86ad9244befd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
